// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1EwwBGfoTbrI_H65QBsLWXB--OwTT7Xc',
    appId: '1:221207954990:web:904eaa5e697afb204881bf',
    messagingSenderId: '221207954990',
    projectId: 'airbeb-91b7e',
    authDomain: 'airbeb-91b7e.firebaseapp.com',
    storageBucket: 'airbeb-91b7e.firebasestorage.app',
    measurementId: 'G-B5TKJ2YX2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB86SJ38DacTr0GxfU4RFoiPuL6fj6yp8',
    appId: '1:221207954990:android:ec5ffedaa2778b974881bf',
    messagingSenderId: '221207954990',
    projectId: 'airbeb-91b7e',
    storageBucket: 'airbeb-91b7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa2lEvTErE2Z0Ztd6NySk2ae2BFd51AYc',
    appId: '1:221207954990:ios:d6a7dd3bd9dbe6654881bf',
    messagingSenderId: '221207954990',
    projectId: 'airbeb-91b7e',
    storageBucket: 'airbeb-91b7e.firebasestorage.app',
    iosBundleId: 'com.example.airbeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa2lEvTErE2Z0Ztd6NySk2ae2BFd51AYc',
    appId: '1:221207954990:ios:d6a7dd3bd9dbe6654881bf',
    messagingSenderId: '221207954990',
    projectId: 'airbeb-91b7e',
    storageBucket: 'airbeb-91b7e.firebasestorage.app',
    iosBundleId: 'com.example.airbeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1EwwBGfoTbrI_H65QBsLWXB--OwTT7Xc',
    appId: '1:221207954990:web:a7dc898342a1e92a4881bf',
    messagingSenderId: '221207954990',
    projectId: 'airbeb-91b7e',
    authDomain: 'airbeb-91b7e.firebaseapp.com',
    storageBucket: 'airbeb-91b7e.firebasestorage.app',
    measurementId: 'G-0X9R8WB2NJ',
  );
}
